server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-security
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true