server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-security
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: SpringBoot-Security-Client
            authorization-grant-type: authorization_code
            scope: openid

        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/SpringBoot-Security-Realm
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/SpringBoot-Security-Realm
